### ISSUE TITLE
Issues remapping 'u' Key

### ISSUE THREAD

**Issue by ataylor-us** [Ajatt-Tools/FlexibleGrading#10]
Hey!  Love the add-on, appreciate all the work you've put into it.

My issue is, is that with vim muscle memory, I'll instinctively hit `u` every time I get a card wrong instead of `h`, so I tried remapping it to `~`.

While it does map undo to `~`, it seems that `u` is still mapped to undo which causes me to undo my last review pretty often.

Here's a screenshot of my settings:
<img src="https://github.com/Ajatt-Tools/FlexibleGrading/assets/63012818/1122f4d7-3524-4142-b786-b959cea51120.png" width="450">

I've tried opening and closing Anki to no luck.  My host right now is Arch, and I'm using `anki-bin` from the AUR.  I also have had the same issue on my macOS laptop, which uses whatever Anki is latest in brew.

Let me know if you need more info, or have any ideas for a workaround. Thanks for reading!

**Comment by tatsumoto-ren** [comment]
Hey! `u` is mapped to `undo` in vanilla Anki (when you don't use any add-ons). The add-on doesn't remove this shortcut.

**Comment by ataylor-us** [comment]
> Hey! `u` is mapped to `undo` in vanilla Anki (when you don't use any add-ons). The add-on doesn't remove this shortcut.

Oops!  Thanks so much for the info.

In case anyone finds this--

I was unable to find the key mapping `"u"`in the config for the [Customize Keyboard Shortcuts](https://ankiweb.net/shared/info/24411424) add-on to try and unmap. So my workaround is now just to map `u` to the "Again" key in FlexibleGrading, which will do for now.

Closing this, thanks again!

**Comment by tatsumoto-ren** [comment]
> my workaround is now just to map u to the "Again" key in FlexibleGrading, which will do for now.

I think we can simply nuke the default hotkey for *undo* when FlexibleGrading reassigns shortcuts.  Can be done with a simple change in code.
