### ISSUE TITLE
[i] button for editing card not work

### ISSUE THREAD

**Issue by ghost** [Ajatt-Tools/FlexibleGrading#2]
Anki Version ⁨2.1.50 (67c1f736)⁩
Python 3.10.4 Qt 5.15.2 PyQt 5.15.6

I'm using anki-git package from AUR.

**Comment by tatsumoto-ren** [comment]
I can reproduce. Can't tell why it happens yet.

**Comment by tatsumoto-ren** [comment]
Figured it out. By default `i` is bound to `Reviewer.on_card_info`, so the two shortcuts conflict. At the same time, by default you can invoke the Edit Current dialog by pressing `e`. I'm going to remove the `i` shortcut because it's redundant.
