### ISSUE TITLE
New Update Error

### ISSUE THREAD

**Issue by Armaniac** [Ajatt-Tools/FlexibleGrading#3]
Hello,

Thank you for keeping the plug-in upto date, however the most recent update has caused the plug-in to stop working. 

Please take a look at the error in the screenshot attached.

Best regards,
Arman
<img width="424" alt="Screenshot 2022-12-05 at 16 05 17" src="https://user-images.githubusercontent.com/16627832/205572516-6192953d-c45b-4d0b-980d-87a55ea7370d.png">

**Comment by tatsumoto-ren** [comment]
Sorry I forgot to add [issue.md](https://github.com/Ajatt-Tools/FlexibleGrading/blob/main/.github/ISSUE_TEMPLATE/issue.md), but now I have.

I can't reproduce the error, so can't tell anything yet. Try updating the addon and updating Anki as well.

**Comment by sdufus** [comment]
I'm having the a similar issue as well. Running Anki 2.1.54 qt5 on Windows 10 Pro x64.

![image](https://user-images.githubusercontent.com/80500984/205789583-65bc2838-8711-47b9-bce6-a567e90f0452.png)
